### ISSUE TITLE
Software Sources is broken in the PPA

### ISSUE THREAD

**Issue by pizzadude** [linuxmint/alpha-testing#1]
Currently, mintsources is broken in the daily builds PPA. 

Here is the terminal output of trying to launch it:

Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1691, in <module>
    Application().run()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 772, in __init__
    self.apt = mintcommon.APT(self._main_window)
AttributeError: module 'mintcommon' has no attribute 'APT'

Not a huge issue as I mostly use the CLI to edit sources, but I think it should be noted nonetheless.

**Comment by pizzadude** [comment]
Edit: Adding this to /etc/apt/preferences.d/mint-daily-builds-ppa.pref and upgrading fixes it.
`Package: *
Pin: release o=LP-PPA-linuxmint-daily-build-team-daily-builds
Pin-Priority: 700
`
Closing.

**Comment by LinuxOnTheDesktop** [comment]
I too encountered this problem with the daily builds.
