### ISSUE TITLE
"Recent files" list shows in wrong menu

### ISSUE THREAD

**Issue by Atrosha** [linuxmint/alpha-testing#12]
Linux Mint 19.1 Cinnamon
Linux kernel: 4.15.0-48-generic
Cinnamon version 4.0.10
current daily build
x64

After update from alpha-testing repository, reboot, watch movie and start menu opened, I found this list of elements (moviefilename + clearlist) added to current list in "Internet" category. The very first menu category I'd selected.

It's non-critical because all back to normal by selecting differ menu category after that.

It seems what start menu + recent files initialization goes wrong.

**Comment by JosephMcc** [comment]
Could you let us know if you still see this on a more up-to-date daily build. I can't reproduce it and we need some way to do that to really look at fixing it.

**Comment by itzexor** [comment]
I was sitting on this one for a while waiting to see what was happening on master. Forgot to respond here until i got another notification, sorry.
