### ISSUE TITLE
Overlapping tooltips in very latest PPA build

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/alpha-testing#15]
![image](https://user-images.githubusercontent.com/47056543/59167219-117f0300-8b28-11e9-8758-ca0d8033b139.png)

I got this by hovering over the network applet and then hovering over the Update Manager.

If this is by design, then I submit it is not good design; also, it's inconsistent, in that it happens only sometimes (depending on just how one moves the mouse) and, perhaps, in that it affects only certain (combinations of) icons.

Thanks.

**Comment by JosephMcc** [comment]
This is an issue on latest master I keep seeing. It happens pretty much only around systray.

**Comment by LinuxOnTheDesktop** [comment]
Fixed in [this build](https://github.com/linuxmint/alpha-testing/issues/16#issuecomment-500427613) supplied by Clem. That build is not (yet?) in the PPA. I am unsure whether to close this issue.

**Comment by clefebvre** [comment]
It is now.
