### ISSUE TITLE
Hard hang on unlock

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/alpha-testing#17]
The computer (a 2018 laptop with Intel graphics) had been suspended for half an hour or so. Upon entering my password into the lock screen, the computer hung, showing my desktop, but faded, and the keyboard icon from the lock screen. I took a photo using a phone but the photo is no use (partly because the flash reflected off the screen). I had to 'raise elephants'. I am using [this build](https://github.com/linuxmint/alpha-testing/issues/16#issuecomment-500427613). I am going to switch to the versions of mutter and Cinnamon in the alpha PPA, because they might not hang and I can't afford to have my computer hang, I am afraid.

EDIT: I can't find anything good in my logs but then again I am not very good at reading the logs.

**Comment by clefebvre** [comment]
Do you get a freeze after playing a video fullscreen and closing it? With mpv for instance.

**Comment by LinuxOnTheDesktop** [comment]
No, I don't think anything full screen (not even a browser in full screen mode) was running.

**Comment by clefebvre** [comment]
no, I mean, do you get the same issue with fullscreen unredirected apps? (i.e. not with the screensaver).

**Comment by clefebvre** [comment]
@itzexor is chasing a regression in muffin which causes freezes when unredirected fullscreen apps are closed.

**Comment by LinuxOnTheDesktop** [comment]
> no, I mean, do you get the same issue with fullscreen unredirected apps? (i.e. not with the screensaver).

Well, as said, I no longer have the particular build that was at issue. But, on my current build, I just tried mpv, full screen and closing it worked fine (though, since the app _was_ full screen, I used a keyboard shortcut to close it). I don't know what 'unredirected' means. I have compositing disabled for full-screen windows.

By the way: is mpv - which I don't normally use - meant to behave as follows? When I run it, it opens a window containing text that says 'drop files or URLs to play here' and when I click that text, the window goes blank and a second window appears that looks the same as the old one did. Screenshot:

![Screenshot_20190611_103843](https://user-images.githubusercontent.com/47056543/59261412-50e74580-8c35-11e9-9622-b6365ba8d595.png)

**Comment by pizzadude** [comment]
@LinuxOnTheDesktop unredirected is the fancy technical term for "compositing disabled for fullscreen apps" as far as i know.

about mpv, it's supposed to have a minimalistic interface (i usually use SMPlayer as a frontend though) and the bug you describe about it opening another window is probably a bug in the ubuntu package for mpv, i use a more up-to-date mpv from a ppa so I haven't encountered this issue.

**Comment by pizzadude** [comment]
@LinuxOnTheDesktop on an unrelated note, would you mind sharing your wallpaper? xD

**Comment by LinuxOnTheDesktop** [comment]
@pizzadude : thank you for the information. [Wallpaper](https://i.postimg.cc/HLspDrjf/Abstract.jpg).

**Comment by clefebvre** [comment]
@itzexor's fix is in the PPA now: https://github.com/linuxmint/muffin/commit/6b11adbaec9c1c2295584df441517e27bdaff9cd. Can you still reproduce the issue?

**Comment by pizzadude** [comment]
@clefebvre I've been using the mint daily ppa for a while today and it seems stable, but I'm not sure if I had the same issue as @LinuxOnTheDesktop though I did have issues where Cinnamon froze before, requiring me to manually restart it.

**Comment by LinuxOnTheDesktop** [comment]
With the latest PPA build, so far I have not seen the problem again. So, I'm closing the issue.
