### ISSUE TITLE
Syslog: 'Error: Requiring NemoPreview'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/alpha-testing#18]
Since I have been running the alpha (and I am on what seems to be the latest PPA build), I see a couple of instances of the following in my syslog; I thought  that fact might be worth reporting.

> JS ERROR: Error: Requiring NemoPreview, version none: Typelib file for namespace 'XreaderView', version '1.5' not found#012@/usr/share/nemo-preview/js/ui/fallbackRenderer.js:31:7#012@/usr/share/nemo-preview/js/ui/mimeHandler.js:28:7#012@/usr/share/nemo-preview/js/viewers/font.js:28:7

I am unable to reproduce the issue at will. Running Nemo and navigating to a folder containing PDFs does not seem to generate the log entry.

**Comment by clefebvre** [comment]
That might help https://github.com/linuxmint/nemo-extensions/pull/323

**Comment by LinuxOnTheDesktop** [comment]
Closing because Mint 19.3 is out and the problem reported here has been solved.
