### ISSUE TITLE
Alt-tab problems

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/alpha-testing#19]
Sometimes, and especially when my laptop is on battery power, the alt-tab display seems sluggish. Indeed sometimes the alt-tab keypress seems to be entirely ignored. I have this problem whether I had set a delay of zero or a delay of 50 in the alt-tab options. I have alt-tab mode set to 'cover-flow 3D'. I think that I encountered this problem before I started using the alpha (and I am on the latest PPA build) but it seems to me that pre-alpha the problems were less severe. It might be worth seeing whether the problem is reproducible at Mint's end.

OS: Linux Mint 19.1 Tessa x86_64 
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th 
Kernel: 5.1.9-050109-generic 
Resolution: 2560x1440 @ 60.01Hz 
DE: Cinnamon 4.0.10 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark-trans (Mint-Y-Dark-BB_hack) 
Theme: Mint-Y-Dark [GTK2/3]

**Comment by clefebvre** [comment]
Can you make sure this is specific to the PPA version? You can find debs for 4.0 and 4.0-maintenance at https://github.com/linuxmint/cinnamon/issues/8454#issuecomment-493608833.

**Comment by LinuxOnTheDesktop** [comment]
@clefebvre

The problem is _intermittent_, so it might take me a long time to establish whether the problem beset those other two versions you mention.

So I propose to leave this issue open in case anyone else has a similar problem (though, of course, close it if you like).

I see no [issue in the Cinnamon repo](https://github.com/linuxmint/cinnamon/issues) that seems similar to the problem, although there is [this one](https://github.com/linuxmint/cinnamon/issues/8543) - by me, and closed, and seemingly fixed - in the alpha tracker.

**Comment by LinuxOnTheDesktop** [comment]
Closing because, perhaps because of new builds, I have not encountered the problem for a fairly long time.
