### ISSUE TITLE
Cinnamon crash, involving muffin

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/alpha-testing#20]
On what is at the time of writing the latest PPA build, Cinnamon crashed: the system froze for a few seconds and then Cinnamon reported a crash and prompted me to restart it. 

**Syslog entry**

> [27006.471908] cinnamon[30150]: segfault at 18 ip 00007f1f5e968355 sp 00007fffae11d2b0 error 4 in libmuffin.so.0.0.0[7f1f5e8ff000+bc000]

**Cinnamon log entry** (after the crash): nothing relevant, perhaps because Cinnamon had been restarted.

**What I did immediately before the crash occured**

I had ended up somehow - this is itself a bug, it seems - with two entries for the Update Manager in the Grouped Window List, when no Update Manager windows were in fact open. I tried a few times, to no effect, to close the Window List previews for those non-existent windows. Then the crash occured.

**My system**

OS: Linux Mint 19.1 Tessa x86_64 
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th 
Kernel: 5.1.9-050109-generic 
Resolution: 2560x1440 @ 60.01Hz 
DE: Cinnamon 4.0.10 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark-trans (Mint-Y-Dark) 
Theme: Mint-Y-Dark [GTK2/3] 
Icons: Paper [GTK2/3] 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 
Memory: 3442MiB / 15928MiB

**Comment by clefebvre** [comment]
Can we get the stack trace from mintreport and the ~/.xsession-errors?

**Comment by LinuxOnTheDesktop** [comment]
Sorry: I have only just seem the comment - requesting the data - above. In recent weeks (builds) I have not encountered the problem.
