### ISSUE TITLE
MintSources does not make it easy to switch to and from the alpha

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/alpha-testing#23]
Unless I am missing something, _multiple package selection_ [remains impossible](https://github.com/linuxmint/mintsources/issues/173) in the window for downgrading foreign packages (Sources -> Maintenance). That makes it harder to switch between Mint stable (which I need sometimes exactly because it is stable) and the alpha version (for testing).

**Comment by miDeb** [comment]
To switch between alpha and stable you could use ppa-purge or Timeshift.

**Comment by clefebvre** [comment]
Please don't duplicate issues (that one's your own even). Also this github repository is only to flag regressions.
