### ISSUE TITLE
Search in menu is broken

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/alpha-testing#27]
Latest updates, search behaviour is different (and that doesn't mean better) than before.
"box" doesn't find VirtualBox anymore,
"berichte" doesn't find Systemberichte anymore,
"c-p" doesn't find Synaptic-Paketverwaltung anymore, ...

**Comment by clefebvre** [comment]
This is by design https://github.com/linuxmint/cinnamon/commit/d40ba4f900da90f09ecda78f3b139f7bef0fd4cf.
