### ISSUE TITLE
cinnamon-session: 'We failed, but the fail whale is dead'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/alpha-testing#29]
var/log/syslog:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`cinnamon-session CRITICAL: t+1761.84121s: We failed, but the fail whale is dead. Sorry....`

cinnamon
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`4.2.0-unstable-201906301745~ubuntu18.04.1`

cinnamon-session
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`4.2.1-unstable-201907040821~ubuntu18.04.1`

**Comment by clefebvre** [comment]
Yeah ok, but why, what happened, how do you reproduce?

**Comment by LinuxOnTheDesktop** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;Ah yes; sorry.

&nbsp;&nbsp;&nbsp;&nbsp;Nearby log entries reveal the problem was at shutdown; and it may have been a forced (Raising Elephants) shutdown that I performed because of an Alt-tab task switcher hang. (Certainly I had such a hang at some point and had to force the shutdown. I have task switcher set to coverflow3-3d). Relevant bit of the log:

![image](https://user-images.githubusercontent.com/47056543/60900854-d544dc80-a264-11e9-8b84-89cb38f8c987.png)

**My system**

OS: Linux Mint 19.1 Tessa x86_64 
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th 
Kernel: 5.1.14-050114-generic 
Uptime: 13 hours, 22 mins 
Packages: 3176 (dpkg), 3 (snap) 
Shell: bash 4.4.20 
Resolution: 2560x1440 @ 60.01Hz 
DE: Cinnamon 4.2.0 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark-trans (Mint-Y-Dark-BB_hack) 
Theme: Mint-Y-Dark [GTK2/3] 
Icons: Paper [GTK2/3] 
Terminal: xfce4-terminal 
Terminal Font: InconsolataGo 12 
CPU: Intel i7-8550U (8) @ 1.800GHz 
GPU: Intel UHD Graphics 620 
Memory: 2927MiB / 15928MiB 
Disk (/dev/nvme0n1p4): 14G / 40G (37%) 
Disk (/dev/nvme0n1p2): 154G / 405G (41%) 
Disk (udev): 0 / 7.8G (0%)

**Comment by LinuxOnTheDesktop** [comment]
I've just seen the message in the log again. It seems that (as before) the problem was during shutdown.

![image](https://user-images.githubusercontent.com/47056543/61054013-92127700-a3e6-11e9-9610-aa0fc98e50bb.png)

[xsesh.txt](https://github.com/linuxmint/alpha-testing/files/3382166/xsesh.txt)
