### ISSUE TITLE
Cinnamon control center not working

### ISSUE THREAD

**Issue by arghaya** [linuxmint/alpha-testing#33]
Hi Team
Recently switched to this repo, facing this issue.
On clicking on system settings it's not opening, on opening via terminal it's not a complete menu as shared in screenshots.
Please check. 

![image](https://user-images.githubusercontent.com/19197880/84922386-66fad200-b0e3-11ea-9ddb-a4b5c4a6dded.png)
![image](https://user-images.githubusercontent.com/19197880/84922639-c1942e00-b0e3-11ea-9ecc-5eee0ee757c3.png)

**Comment by mtwebster** [comment]
cinnamon-settings, not cinnamon-control-center.  This is only used for debugging our remaining C modules (most are in python, in the cinnamon package now).

**Comment by arghaya** [comment]
Thanks @mtwebster for correcting, on opening cinnamon-settings, I am getting this error.
On clicking on "System settings" in menu, nothing pops up.
 
![image](https://user-images.githubusercontent.com/19197880/84924972-e5a53e80-b0e6-11ea-98be-278105b5182d.png)

**Comment by mtwebster** [comment]
Thanks - this is a regression, can you try this: 
https://github.com/linuxmint/cinnamon/commit/9c02b9c4e4cec6fa3035209dba8859425dfc4049

Also, what distro are you on?

Can you tell me the version of 'gobject-introspection' and 'python3-gi'?

Please use https://github.com/linuxmint/cinnamon for any new issues related to cinnamon or related repos for specific packages (if you know what they are), this repo isn't used for normal reports.

**Comment by arghaya** [comment]
I am on Ubuntu 18.04
'gobject-introspection'  isn't installed, python3-gi is 3.26.1-2ubuntu1.

Let me install gobject-introspection and then check

**Comment by arghaya** [comment]
![image](https://user-images.githubusercontent.com/19197880/84928734-821e0f80-b0ec-11ea-9cca-f710ffac4f35.png)

Cool working fine now. Thanks!!

**Comment by mtwebster** [comment]
Cool np
