### ISSUE TITLE
Keyboard navigation is not working correctly in the "lock" screen

### ISSUE THREAD

**Issue by orbitalchicken** [linuxmint/alpha-testing#34]
On a multi-users setup, in the lock screen (CTRL+ALT+L)...
- I press TAB, TAB: the "go to the main login screen / show all users" icon is highlighted (correct)
- I press ENTER: is display "invalid password" (wrong: it should go to the login screen showing all users)
Affected versions 19.x, 20.x

**Comment by leigh123linux** [comment]
File it against https://github.com/linuxmint/cinnamon-screensaver/issues

**Comment by orbitalchicken** [comment]
Thanks. I did it: https://github.com/linuxmint/cinnamon-screensaver/issues/393
