### ISSUE TITLE
The negative character used by the Mint Calculator is not a correct symbol.

### ISSUE THREAD

**Issue by antrrax** [linuxmint/alpha-testing#4]
I install clear distro Mint 19.1 Cinnamon x64

$sudo add-apt-repository ppa:linuxmint-daily-build-team/daily-builds
$sudo apt update
$sudo apt full-upgrade

************

### The negative character used by the Mint Calculator is not a correct symbol.

************
1) Open the Mint calculator and make an calculation with negative result. EX: 5-10 = -5
2) Copy and paste this result into Libre Office Calc for cells B2 and B3
3) In cell B5 of Calc put this formula = SUM (B2: B3)

<a href="https://ibb.co/FYRMtYH"><img src="https://i.ibb.co/myfw7yN/Screenshot-from-2019-04-07-09-43-05.png" alt="Screenshot-from-2019-04-07-09-43-05" border="0"></a>

The result is zero, but should be -10, since the symbol used by the Mint calculator is String not a Numeric value.

****************

Another example
1) Open the xed and type "-"
2) Open the Mint calculator and make an calculation with negative result. EX: 5-10 = -5
3) Copy and paste this result to another line of xed
4) "Control + F" and search for the term "-"

 <a href="https://ibb.co/wQChmxm"><img src="https://i.ibb.co/6tb0CfC/Screenshot-from-2019-04-07-20-32-12.png" alt="Screenshot-from-2019-04-07-20-32-12" border="0"></a>

You only find one result, but it should be 2, because the symbol used by the Mint calculator is an inappropriate symbol.

**Comment by clefebvre** [comment]
Thanks, however this isn't a regression and it should be reported upstream to the GNOME project.
