### ISSUE TITLE
Conky disappears periodically

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/alpha-testing#7]
```
Cinnamon version (cinnamon --version) 4.0.10
Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
Graphics hardware and driver used: Intel UHD Graphics 620 3.0 Mesa 18.2.8
32 or 64 bit: 64
[x.txt](https://github.com/linuxmint/cinnamon/files/3133715/x.txt)
 ```

**Issue**

Every so often - every twenty minutes? - my conky disappears (becomes invisible), although its process is still running. Conky does not seem to regain visibility without user intervention. (See further below.)

**Steps to reproduce**

To my knowledge:
Install alpha
Have conky

**Expected behaviour**

A persistent conky!

**Other information**

Sometimes but not always: upon killing the conky process and restarting conky, conky remains invisible.

In my conky config file: `own_window_type = 'dock'`

Kernel: 5.0.10-050010-generic
conky-std 1.10.8
Mint's Vsync method: 'Presentation Time' (though I have no idea what that means!).

**Comment by pizzadude** [comment]
@LinuxOnTheDesktop I haven't tested this long enough, but try "own_window_type desktop" instead.

**Comment by LinuxOnTheDesktop** [comment]
@pizzadude 

Thanks, but (1) conky is not the only program affected, (2) I am using that setting in my conky already, (3) I am not using the alpha at the moment - because it had too many problems for daily use and because the developers do not seem at present to be looking at the bug reports.

**Comment by pizzadude** [comment]
@LinuxOnTheDesktop Yeah, hopefully they look at the bug reports eventually but I feel reluctant to bug them about it at the moment. The only issues I have are laggy lockscreen, desklet problem, and the occasional crash.

**Comment by LinuxOnTheDesktop** [comment]
Desklets: the underlying cause here might be the same as in my case with Conky (and with Rainlendar). Yes, the performance has improved a lot, and various small bugs seem to have been fixed.

**Comment by clefebvre** [comment]
@LinuxOnTheDesktop we've gone through massive changes recently, sorry about the delay. Can you retest with the new builds coming today?

**Comment by LinuxOnTheDesktop** [comment]
Hopefully I can retest tomorrow.

**Comment by clefebvre** [comment]
thanks

**Comment by LinuxOnTheDesktop** [comment]
Cinnamon 4.0.10
Daily build from a few minutes ago.

The problem with Conky not showing and indeed the problem with the Rainlendar desktop calendar not showing do seem to be fixed. However, for some twenty seconds just now, the minimize buttons on the windows of various applications stopped working. I'll file a bug report about that if the problem reoccurs.
