### ISSUE TITLE
Doubled dropbox icon

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/alpha-testing#8]
* Cinnamon version (cinnamon --version) 4.0.10
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19.1
 * Graphics hardware *and* driver used: Intel UHD Graphics 620 3.0 Mesa 18.2.8
 * 32 or 64 bit: 64
 * Attach /home/<username>/.xsession-errors, or /var/log/syslog
[x.txt](https://github.com/linuxmint/cinnamon/files/3133672/x.txt)

**Issue**

I see double DropBox icons after installing the alpha and rebooting. I did not see this before. Only one DropBox process seems to be running. Ending DropBox and restarting it solved the problem. Restarting Cinnamon did not reintroduce the problem. Yet perhaps the problem will reoccur.

Screenshot:
![image](https://user-images.githubusercontent.com/47056543/57003565-8a9d4900-6bbf-11e9-9b96-5f9672c5a5c1.png)

**Steps to reproduce**

Have DropBox installed.
Install alpha of Cinnamon.
Reboot.

**Expected behaviour**

There should be only one Dropbox icon.

**Other information**

EDIT: I have just installed the latest alpha, and rebooted. There is only _one_ Dropbox icon. If the matter stays this way, then I will close this issue.
(Also, fixed a typo or two.)

**Comment by JosephMcc** [comment]
Are you seeing the issue anymore? Can it be closed?

**Comment by LinuxOnTheDesktop** [comment]
I no longer have this particular problem. However, the Rainlendar icon does not appear at all until Cinnamon is restarted and even then the icon is much too small. Still, that second (Rainlendar) problem is not a regression (and I thought I filed a bug report for it, against Cinnamon non-alpha, but I can't manage to find that report).

**Comment by JosephMcc** [comment]
Cool, thank you.

**Comment by LinuxOnTheDesktop** [comment]
The problem of double dropbox icons reappeared, with the two icons each showing Dropbox was working; and Cinnamon was pegged at some 7-9% of CPU load. I uninstalled and reinstalled Dropbox and thus far I have but a single icon. However, (1) that icon is tiny. Moreover, (2) when installing the repository version of Dropbox, the progress window was too small: it truncated text. Further, (3) the .deb from the Dropbox website - which is a more recent version - silently failed to install.

Possibly 3 is not Mint's fault. 1 and 2, and the original problem of double-icons (call that problem 0) and constant cpu usage (call that '0b') do seem to be. Please note that Dropbox is popular software.
